name: Deploy Changed Databricks Bundles

on:
  pull_request:
    types: [closed]
    branches:
      - main  # or your default branch

jobs:
  deploy-changed-bundles:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    env:
      # Set the source branch name as an environment variable
      prefix: ${{ github.event.pull_request.head.ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Get changed bundles
        id: changed
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          # Get list of changed files between base and head
          CHANGED_FILES=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} ${{ github.sha }})
          # Extract top-level directories (bundles)
          BUNDLES=$(echo "$CHANGED_FILES" | awk -F/ '{print $1}' | sort | uniq)
          echo "bundles=$BUNDLES" >> $GITHUB_OUTPUT

      - name: Deploy changed bundles
        if: steps.changed.outputs.bundles != ''
        run: |
          for bundle in ${{ steps.changed.outputs.bundles }}; do
            echo "Deploying bundle: $bundle"
            databricks bundle deploy --target dev"
          done
        env:
          DATABRICKS_CLIENT_ID: ${{secrets.DATABRICKS_CLIENT_ID}}
          DATABRICKS_CLIENT_SECRET: ${{secrets.DATABRICKS_CLIENT_SECRET}}
          DATABRICKS_BUNDLE_ENV: dev